[package]
name = "privacy-pools-stwo"
version = "0.1.0"
edition = "2021"

[dependencies]
stwo = { git = "https://github.com/piotr-stec/stwo-fork-keccak", features = ["prover"], branch = "channel/solidity" }
std-shims = { git = "https://github.com/piotr-stec/stwo-fork-keccak", features = ["std"],branch = "channel/solidity"  }
stwo-constraint-framework = { git = "https://github.com/piotr-stec/stwo-fork-keccak", features = ["prover", "std"], branch = "channel/solidity" }
num-traits = "0.2"
thiserror = { version = "2.0.12", default-features = false }
tracing = { version = "0.1.40", default-features = false }
tracing-subscriber = { version = "0.3.18", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
alloy = { version = "0.8", features = ["full", "node-bindings", "rpc-types", "sol-types"] }
tokio = { version = "1.0", features = ["full"] }
itertools = "0.13"

[dev-dependencies]
zkhash = { git = "https://github.com/AntoineFONDEUR/poseidon2.git", branch = "poseidon2-M31" }
eyre = "0.6"

[[test]]
name = "e2e"
path = "e2e/mod.rs"
